// here, I will declare the local variable and global variable...
// So, What ever doesnt gets declares we have to declare globally...
// Like an example let, & const should be declared globally to get printed...
function happyName() {
  let a = "10"; //Here what will happen is that let wont prints because it is local declare..
  const b = "20"; //Here, What will happen it will also not declared because it is local declare..
  var c = "30"; //Here, What will happen it will be declare because var gives you the option to get declared..
}
console.log(happyName);
// 2nd method are that using the for loop method....
// 3rd method also is the function creationa nd declaring out there also it shows the same condition..
// more methods are there like...
const addTwo = function (num) {
  //what is happening out here is that we are creating one variable
  // and then we are storing out function inside it... i.e also known as {expression}...
  return num + 1;
};
console.log(addTwo(5)); //untill & unless we will not declare the properties in it. It will not give the desired output...
